# dhcp_scope_generator.py
from extras.scripts import Script, ObjectVar, StringVar
from dcim.models import Site
from ipam.models import Prefix, IPRange
from django.contrib.contenttypes.models import ContentType
import ipaddress


class DHCPScopeGenerator(Script):

    class Meta:
        name = "DHCP Scope Generator"
        description = "Generates PowerShell Add-DhcpServerv4Scope commands from site prefixes and DHCP IP ranges."
        commit_default = False

    site = ObjectVar(
        model=Site,
        description="Select a site to generate DHCP scope commands for.",
        required=True
    )

    dhcp_server = StringVar(
        description="Target Windows DHCP server hostname or IP (-ComputerName). Leave blank to omit.",
        required=False,
        default=""
    )

    def run(self, data, commit):
        selected_site = data["site"]
        dhcp_server = data["dhcp_server"].strip()

        # NetBox 4.2+: Prefix.site was replaced by generic scope (ContentType + scope_id)
        site_ct = ContentType.objects.get_for_model(Site)
        prefixes = Prefix.objects.filter(
            scope_type=site_ct,
            scope_id=selected_site.id
        ).order_by("prefix")

        if not prefixes.exists():
            self.log_warning(f"No prefixes found for site '{selected_site}'.")
            return "# No prefixes found for the selected site."

        output_lines = [
            f"# DHCP Scope commands for site: {selected_site.name}",
            "# Generated by NetBox DHCP Scope Generator",
            "# Review before executing.",
            "",
        ]

        scope_count = 0

        # Fetch all DHCP-role ranges once; filter by prefix containment in Python
        all_dhcp_ranges = list(
            IPRange.objects.filter(role__slug="dhcp").order_by("start_address")
        )

        for prefix in prefixes:
            net = ipaddress.ip_network(str(prefix.prefix), strict=True)

            # Skip point-to-point and host routes
            if net.prefixlen >= 31:
                continue

            subnet_mask = str(net.netmask)
            scope_name = (
                prefix.description.strip()
                if prefix.description
                else f"{selected_site.name} - {prefix.prefix}"
            )

            # ip_interface handles CIDR notation from NetBox (e.g. "10.20.0.10/24")
            ip_ranges = [
                r for r in all_dhcp_ranges
                if ipaddress.ip_interface(str(r.start_address)).ip in net
                and ipaddress.ip_interface(str(r.end_address)).ip in net
            ]

            if not ip_ranges:
                self.log_info(f"Prefix {prefix.prefix}: no DHCP ranges found, skipping.")
                continue

            output_lines.append(f"# --- Prefix: {prefix.prefix} | {scope_name} ---")

            for ip_range in ip_ranges:
                start_ip = str(ipaddress.ip_interface(str(ip_range.start_address)).ip)
                end_ip   = str(ipaddress.ip_interface(str(ip_range.end_address)).ip)

                range_desc = (
                    ip_range.description.strip()
                    if ip_range.description
                    else f"DHCP {start_ip} - {end_ip}"
                )

                parts = ["Add-DhcpServerv4Scope"]
                if dhcp_server:
                    parts.append(f'-ComputerName "{dhcp_server}"')
                parts += [
                    f'-Name "{scope_name}"',
                    f'-StartRange {start_ip}',
                    f'-EndRange {end_ip}',
                    f'-SubnetMask {subnet_mask}',
                    f'-Description "{range_desc}"',
                    f'-State Active',
                ]

                output_lines.append(" ".join(parts))
                scope_count += 1

            output_lines.append("")

        if scope_count == 0:
            self.log_warning(
                "No DHCP IP ranges found under any prefix for this site. "
                "Verify IP ranges exist with role slug 'dhcp'."
            )
            return "# No DHCP IP ranges found."

        self.log_success(
            f"Generated {scope_count} Add-DhcpServerv4Scope command(s) for '{selected_site.name}'."
        )
        return "\n".join(output_lines)
